// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwg0Z4cfkmXZQ55KYdWUtMiOchnB2RsKA',
    appId: '1:629885777398:web:5cb0b745893be34c6e83d7',
    messagingSenderId: '629885777398',
    projectId: 'newsapp-c6e28',
    authDomain: 'newsapp-c6e28.firebaseapp.com',
    storageBucket: 'newsapp-c6e28.firebasestorage.app',
    measurementId: 'G-GQYT9JS1S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_0EGwPIq9O6WUr4CpJSsk4C3vbxIDvI',
    appId: '1:629885777398:android:d9857ac5518fca8c6e83d7',
    messagingSenderId: '629885777398',
    projectId: 'newsapp-c6e28',
    storageBucket: 'newsapp-c6e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZv6xvRQliKXQYHheDMhY7OrPPEUms5IQ',
    appId: '1:629885777398:ios:1958a1731458a2c06e83d7',
    messagingSenderId: '629885777398',
    projectId: 'newsapp-c6e28',
    storageBucket: 'newsapp-c6e28.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZv6xvRQliKXQYHheDMhY7OrPPEUms5IQ',
    appId: '1:629885777398:ios:1958a1731458a2c06e83d7',
    messagingSenderId: '629885777398',
    projectId: 'newsapp-c6e28',
    storageBucket: 'newsapp-c6e28.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwg0Z4cfkmXZQ55KYdWUtMiOchnB2RsKA',
    appId: '1:629885777398:web:5cebf5819161486b6e83d7',
    messagingSenderId: '629885777398',
    projectId: 'newsapp-c6e28',
    authDomain: 'newsapp-c6e28.firebaseapp.com',
    storageBucket: 'newsapp-c6e28.firebasestorage.app',
    measurementId: 'G-4JGMQ9S59W',
  );
}
